### ISSUE TITLE
缺少说明

### ISSUE THREAD

**Issue by Agnes4m** [bridgeL/nonebot-plugin-ayaka-who-is-suspect#1]
帮助没用啊，不知道如何使用指令
![image](https://user-images.githubusercontent.com/70925546/198462980-97eaadac-6218-4bed-a8e3-6b483997427d.png)
### help、帮助指令
出来的是ayaka的帮助
![image](https://user-images.githubusercontent.com/70925546/198463823-b30ff2c2-a033-4d36-90e2-5467adafe5c4.png)

**Comment by bridgeL** [comment]
来了，发送 **谁是卧底** 试试

**Comment by Agnes4m** [comment]
还有个不太重要的小问题，输入指令`help`,转发信息会有两次谁是卧底
![image](https://user-images.githubusercontent.com/70925546/198505593-19b4e634-58f9-4657-aa5d-ed9d392edc6b.png)
